// Exemplos fictícios: nunca são gravados no banco nem misturados a anúncios reais.
export const exemplos = [
  {
    id: "exemplo-1",
    tipo: "perdido",
    nome_animal: "Bento",
    especie: "Cachorro",
    raca: "Sem raça definida",
    cor: "Caramelo",
    porte: "Pequeno",
    sexo: "Macho",
    descricao:
      "Cachorrinho caramelo, muito dócil, com uma mancha branca no peito. Estava usando uma coleira verde.",
    caracteristicas: "Peito branco e coleira verde",
    cidade: "Brasília",
    bairro: "Sobradinho II",
    referencia: "Próximo à praça do bairro",
    data_ocorrencia: "2026-09-17",
    status: "ativo",
    foto_url: "../assets/img/cachorro.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
  {
    id: "exemplo-2",
    tipo: "encontrado",
    nome_animal: "",
    especie: "Gato",
    raca: "Sem raça definida",
    cor: "Cinza",
    porte: "Pequeno",
    sexo: "Não identificado",
    descricao:
      "Gatinho encontrado perto de uma padaria. É tranquilo e parece estar acostumado com pessoas.",
    caracteristicas: "Olhos claros",
    cidade: "Brasília",
    bairro: "Asa Norte",
    referencia: "Comércio local da quadra SQN 210",
    data_ocorrencia: "2026-09-18",
    status: "ativo",
    foto_url: "../assets/img/gato.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
  {
    id: "exemplo-3",
    tipo: "perdido",
    nome_animal: "Luna",
    especie: "Cachorro",
    raca: "Border collie",
    cor: "Preto e branco",
    porte: "Médio",
    sexo: "Fêmea",
    descricao:
      "Saiu pelo portão no fim da tarde. Atende pelo nome de Luna e é bastante brincalhona.",
    caracteristicas: "Pelagem preta e branca",
    cidade: "Brasília",
    bairro: "Águas Claras",
    referencia: "Perto do parque",
    data_ocorrencia: "2026-09-16",
    status: "ativo",
    foto_url: "../assets/img/luna.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
  {
    id: "exemplo-4",
    tipo: "encontrado",
    nome_animal: "",
    especie: "Cachorro",
    raca: "Sem raça definida",
    cor: "Caramelo",
    porte: "Médio",
    sexo: "Macho",
    descricao:
      "Cachorro encontrado perto da feira. Está bem cuidado e usa coleira azul.",
    caracteristicas: "Coleira azul e ponta das patas brancas",
    cidade: "Brasília",
    bairro: "Taguatinga",
    referencia: "Próximo à feira permanente",
    data_ocorrencia: "2026-09-15",
    status: "ativo",
    foto_url: "../assets/img/cachorro.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
  {
    id: "exemplo-5",
    tipo: "perdido",
    nome_animal: "Nina",
    especie: "Gato",
    raca: "Sem raça definida",
    cor: "Preto e branco",
    porte: "Pequeno",
    sexo: "Fêmea",
    descricao:
      "Gatinha dócil que saiu de casa pela manhã. Atende pelo nome de Nina.",
    caracteristicas: "Focinho branco e cauda preta",
    cidade: "Brasília",
    bairro: "Guará II",
    referencia: "Próximo ao comércio local",
    data_ocorrencia: "2026-09-14",
    status: "ativo",
    foto_url: "../assets/img/gato.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
  {
    id: "exemplo-6",
    tipo: "encontrado",
    nome_animal: "",
    especie: "Cachorro",
    raca: "Sem raça definida",
    cor: "Preto e branco",
    porte: "Médio",
    sexo: "Fêmea",
    descricao:
      "Encontrada sem identificação perto do parque. É brincalhona e sociável.",
    caracteristicas: "Pelagem preta e branca",
    cidade: "Brasília",
    bairro: "Paranoá",
    referencia: "Entrada principal do parque",
    data_ocorrencia: "2026-09-13",
    status: "ativo",
    foto_url: "../assets/img/luna.jpg",
    contato: "Contato indisponível em anúncios de exemplo",
  },
];
